### ISSUE TITLE
关于获取高清图片

### ISSUE THREAD

**Issue by History-exe** [KeElena/miyoushe_emoji#1]
由于想将表情用于制作Telegram Stickers，需要512px的图片，目前有头绪在哪里可以找到吗？

是只可使用waifu2x强行放大吗？

**Comment by KeElena** [comment]
你可以考虑使用Real-ESRGAN实现超分辨率4×
[Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN/blob/master/README_CN.md)里有便携版可执行文件，下载完[RealESRGAN_x4plus.pth](https://github.com/xinntao/Real-ESRGAN/releases/download/v0.1.0/RealESRGAN_x4plus.pth)模型后使用命令(./realesrgan-ncnn-vulkan.exe -i 输入图像.jpg -o 输出图像.png -n 模型名字)获取超分表情
我觉得RealESRGAN超分质量比waifu好

**Comment by History-exe** [comment]
OK，多谢指点。
刚刚我试了一下直接用gimp放大，制作成贴纸之后效果也还可以。

上方的是我制作的，下方是不明作者制作的，不知道他用了什么方法，贴纸很清晰。
![图片](https://user-images.githubusercontent.com/33642965/236440891-f369a236-824a-40ea-aae7-06ce58fc4b3f.png)

试了[Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN/blob/master/README_CN.md)，效果真不错。问题解决了。
